import type { Metadata } from "next";
import "./globals.css";
import '../../public/fonts/Orbitron.css'
import { ViewTransitions } from "next-view-transitions";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">

        <body
          className={`antialiased`}
        >
          <main>

            {children}
          </main>
        </body>
      </html>
    </ViewTransitions>
  );
}
